### ISSUE TITLE
Layouts 📐

### ISSUE THREAD

**Issue by robinmetral** [robinmetral/coffee#14]
Style admin panel [with this](https://codyhouse.co/gem/css-slide-in-panel/)

**Comment by robinmetral** [comment]
Got the panel (*todo: rename Admin into Panel*) to toggle open and closed with a dynamic `styled-components` `display` attribute. (182d0a8205aae4a6c36cba4d588d02e8152a2c78).

Now I need to animate the opening and closing of the panel.
I don't think it's possible with `display`, I could switch to this hack: ([source](https://stackoverflow.com/a/6943704/))
```css
div {
  border: 1px solid #eee;
}
div > ul {
  visibility: hidden;
  opacity: 0;
  transition: visibility 0s, opacity 0.5s linear;
}
div:hover > ul {
  visibility: visible;
  opacity: 1;
}
```
```html
<div>
  <ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
  </ul>
</div>
```

A better animation would be to slide from the right. Two solutions:

1. Either I'd need to set a `width:0;` and transition into `50% width`
  _**Edit:** the problem with transitioning `width` is that the text wraps and unwraps instead of just sliding_
2. Or place the panel outside of the screen to the right (like in [this example](https://www.codementor.io/chrisharrington/how-to-build-a-sliding-menu-using-react-js-and-less-css-du107mpij)).
